services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      MODEL_PATH: /app/models/forecast_model.pkl
      DATA_DIR: /app/m5_data
    volumes:
      - ./models:/app/models
      - ./m5_data:/app/m5_data
    restart: unless-stopped

  mlflow:
    build: .
    command:
      [
        "mlflow",
        "server",
        "--backend-store-uri",
        "sqlite:////app/mlflow.db",
        "--default-artifact-root",
        "/app/mlruns",
        "--host",
        "0.0.0.0",
        "--port",
        "5000"
      ]
    ports:
      - "${MLFLOW_PORT:-5001}:5000"
    volumes:
      - .:/app
    restart: unless-stopped

  airflow-init:
    image: apache/airflow:2.9.3
    environment:
      AIRFLOW_HOME: /opt/airflow/airflow_home
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas==2.1.3 scikit-learn==1.3.2 mlflow==2.9.2 matplotlib==3.8.2"
    command: >
      bash -c "airflow db migrate &&
               airflow users create
               --username admin
               --password admin
               --firstname Admin
               --lastname User
               --role Admin
               --email admin@example.com || true"
    volumes:
      - .:/opt/airflow/project
      - airflow_home:/opt/airflow/airflow_home

  airflow-webserver:
    image: apache/airflow:2.9.3
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW_HOME: /opt/airflow/airflow_home
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/project/dags
      PYTHONPATH: /opt/airflow/project
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas==2.1.3 scikit-learn==1.3.2 mlflow==2.9.2 matplotlib==3.8.2"
    command: webserver
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/airflow/project
      - airflow_home:/opt/airflow/airflow_home
    restart: unless-stopped

  airflow-scheduler:
    image: apache/airflow:2.9.3
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW_HOME: /opt/airflow/airflow_home
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/project/dags
      PYTHONPATH: /opt/airflow/project
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas==2.1.3 scikit-learn==1.3.2 mlflow==2.9.2 matplotlib==3.8.2"
    command: scheduler
    volumes:
      - .:/opt/airflow/project
      - airflow_home:/opt/airflow/airflow_home
    restart: unless-stopped

volumes:
  airflow_home:
