FROM apache/airflow:2.9.3

USER airflow

ENV PYTHONWARNINGS=ignore::UserWarning:_distutils_hack

RUN pip install --no-cache-dir \
    pandas==2.1.3 \
    scikit-learn==1.3.2 \
    mlflow==2.9.2 \
    matplotlib==3.8.2
