FROM apache/airflow:2.9.3

USER airflow

ENV PYTHONWARNINGS=ignore::UserWarning:_distutils_hack

RUN pip install --no-cache-dir \
    pandas==2.2.3 \
    scikit-learn==1.6.1 \
    mlflow==3.10.1 \
    matplotlib==3.9.4
